### ISSUE TITLE
Feature Request: Default to appImage if missing subsystem dependency is detected.

### ISSUE THREAD

**Issue by turbo124** [beganovich/snappdf#13]
If a missing subsystem dependency is detected, can appImage be used as default?

**Comment by beganovich** [comment]
Hey there, how this correlates to this? https://github.com/beganovich/snappdf/issues/12#issuecomment-771595302

**Comment by turbo124** [comment]
The idea here is that when the package is installed, it detects the system and sets the correct path to the binary that _should_ work.

**Comment by beganovich** [comment]
_Discussed internally_. ungoogled-chrome, unfortunately, won't work on most of the shared hostings, cause they use older host dependencies.
