### ISSUE TITLE
Optimization for local setups with Snakeoil SSL encryption

### ISSUE THREAD

**Issue by cdahinten** [beganovich/snappdf#14]
Hello @beganovich,

after several hours of trying to render PDF from inside of Invoice Ninja with snappdf I found out, that the HTML requests of pictures referenced by Invoice Ninja won't pass as valid https requests thru chromium due to certificate errors.

I use Ubuntu 20.04.2 LTS Server on Raspberry 4 8B with ungoogled-chromium v84+ with snakeoiled SSL Certificate. (https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium) Chromium leaves out / doe not load the Images in the pdf due to certificate errors. See here: 
https://forum.invoiceninja.com/t/company-logo-not-display-within-invoice/5218/35

I added:
export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --ignore-certificate-errors"

with:
sudo nano /etc/chromium.d/default-flags 

to get the images show up in the PDF. Do you think, it would make sence to add this flag into the standard query, or even better to have this flag triggered by a environment-variable e.g. SNAPPDF_SNAKEOIL_SSL=true?

**Comment by beganovich** [comment]
Hey there, I think it's safe for this to be in the core of snappdf. This will be added to the todo list & pushed as an update shortly.

Thanks for suggesting this 👍

**Comment by beganovich** [comment]
This is part of snappdf since 1.6.0 🎉

https://github.com/beganovich/snappdf/releases/tag/v1.6.0
