### ISSUE TITLE
Environment variables operational? 

### ISSUE THREAD

**Issue by cdahinten** [beganovich/snappdf#15]
Hello @beganovich,

while configuring a Invoice Ninja V5 test installation Ubuntu 20.04.2 LTS. I was not able to route snappdf to another chromium installation (https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium)

$ sudo nano /etc/environment

SNAPPDF_EXECUTABLE_PATH="/usr/bin/chromium"
SNAPPDF_SKIP_DOWNLOAD=true

$ source /etc/environment
$ echo $SNAPPDF_EXECUTABLE_PATH

reboot+relogin.

But Invoice Ninja always used the downloaded chrome with snappdf download and not the given path. I also pulled a new chrome during recent updates. As a "hack" I replaced the snappdf chrome-binary with a symlink to my local chromium, but I was wondering, if I made a mistake or overlooked something.

Do you have a idea, what could be wrong?

**Comment by beganovich** [comment]
Hey there, I followed the steps you provided and it seems to not work for me either (Ubuntu 20.04). However, setting these variables in the .bashrc or .profile.d/ seems to be working just fine. Can you try one of the following: 

Note: This is only applicable for users using standalone snappdf. For Invoice Ninja, the push will be provided shortly which will let you set these variables in the .env file 👍

https://www.tecmint.com/set-unset-environment-variables-in-linux/

**Comment by beganovich** [comment]
Hey there, I followed the steps you provided and it seems to not work for me either (Ubuntu 20.04). However, setting these variables in the .bashrc or .profile.d/ seems to be working just fine. Can you try one of the following:

https://www.tecmint.com/set-unset-environment-variables-in-linux/

**Comment by cdahinten** [comment]
Hey @beganovich,

all of the recommend places worked for me as an env-command shows, but I missed some out details:

I thought the environment-variables shoud be available to the www-data user, but thats an no-login one. So there is no success of writing .bashrc or .profile.d/ nor creating ~/.profile since there is no session.

sudo -u www-data env is not listing these SNAPPDF_EXECUTABLE_PATH e.g. in any case.

I succeeded in setting these snappdf-vars in the server settings of ngnix by adding these lines to the server{}-block:

fastcgi_param SNAPPDF_EXECUTABLE_PATH '/usr/bin/chromium';
fastcgi_param SNAPPDF_SKIP_DOWNLOAD true;

This could be an advise for the documentation of snappdf – it works really stable an fast on a Raspberry 4 Pi 8GB test-setup.

**Comment by beganovich** [comment]
Hey there, thanks for the awesome feedback & help with this. This is now part of the documentation. 👍

Ref. commit: https://github.com/beganovich/snappdf/commit/34f8d2e2cedecb4d6f3de42dd657e20d46b01500
