### ISSUE TITLE
The process has been signaled with signal "6".

### ISSUE THREAD

**Issue by bajki** [beganovich/snappdf#20]
Hi i have problem with cyberpanel on centos 8 / ubuntu.

Invoice ninja v5.2.16
php 8.0.8 || php 7.4 || php 7.3

PDF_GENERATOR=snappdf
PHANTOMJS_PDF_GENERATION=false

I'm getting this process error.
![ninja](https://user-images.githubusercontent.com/24210611/128422428-c28fbc08-e9d2-42f4-b4c3-4073f462c22a.png)

If i run process command from terminal it works, but from Symfony Process i get error.

**Comment by beganovich** [comment]
Hey, 

Thanks for reporting this, however, this is the wrong place to report with this kind of context. Please post this issue to the Invoice Ninja issues page.

Thanks :+1:
