### ISSUE TITLE
Latest version of chrome not rendering css/js

### ISSUE THREAD

**Issue by turbo124** [beganovich/snappdf#22]
The latest version of chrome downloaded by Snap is broken. It no longer renders js/css

It seem the version that is downloaded is from bleeding edge, perhaps it would be better to use the stable channel if that URL can be resolved.

This is a high impact bug.

**Comment by beganovich** [comment]
Thanks for reporting. This is the nature of Chromium itself, it doesn't have a stable or unstable version only daily or nightly builds AFAIK. 

From the docs: 

> Note: snappdf will download & use latest build of Chromium. Since Chromium itself doesn't have stable or unstable release, browser itself can be buggy or possibly broken. We don't take any responsibility for that. If security & stability is your top priority, please install Google Chrome stable version & point package to use that.

Perhaps we can switch https://chromium.woolyss.com/ for the download server, will look into :+1:
