### ISSUE TITLE
snappdf in raspberry error

### ISSUE THREAD

**Issue by ArchLinx** [beganovich/snappdf#27]
hi, i think it is possible run snappdf in my raspberry pi 4 but i have this error:

Run:
`./vendor/bin/snappdf convert --html "<h1>Hello world</h1>" save.pdf`

ERROR:

`In Snappdf.php line 232:

  The command "'/srv/http/InvoiceNinja/vendor/beganovich/snappdf/versions/1044052-Linux_x64/chrome-linux/chrome' '--headless' '--disable-gpu'
  '--disable-translate' '--disable-extensions' '--disable-sync' '--disable-background-networking' '--disable-software-rasterizer' '--disable-d
  efault-apps' '--disable-dev-shm-usage' '--safebrowsing-disable-auto-update' '--run-all-compositor-stages-before-draw' '--no-first-run' '--no
  -margins' '--no-sandbox' '--print-to-pdf-no-header' '--hide-scrollbars' '--ignore-certificate-errors' '--print-to-pdf=/tmp/pdf_if6SST.pdf' '
  /tmp/html_KpioDZ.html'" failed.

  Exit Code: 126(Invoked command cannot execute)

  Working directory: /srv/http/InvoiceNinja

  Output:
  ================

  Error Output:
  ================
  sh: line 1: /srv/http/InvoiceNinja/vendor/beganovich/snappdf/versions/1044052-Linux_x64/chrome-linux/chrome: cannot execute binary file: Exe
  c format error
  sh: line 1: /srv/http/InvoiceNinja/vendor/beganovich/snappdf/versions/1044052-Linux_x64/chrome-linux/chrome: Success

convert [--url URL] [--html HTML] [--binary BINARY] [--] <path>`

how to fix ?

regards

**Comment by beganovich** [comment]
Hi there,

Running Snappdf is definitely possible on ARM devices, but built-in downloader won't do it. Make sure to install Chrome or Chromium from your distro repositories and and pass environment variable.

```
SNAPPDF_EXECUTABLE_PATH=/path/to/your/chrome vendor/bin/snappdf
```

**Comment by ArchLinx** [comment]
@beganovich thank you for help :)
for future users whit same issue...
I'm usim manjaro in my rasperry 4

`
pacman -S chromium
add to /etc/environment:
SNAPPDF_EXECUTABLE_PATH=/usr/bin/chromium`

work fine :)
regards

**Comment by ArchLinx** [comment]
For invoiceninja self-hosted need to add
`SNAPPDF_CHROMIUM_PATH=/usr/bin/chromium`
to .env file

regards

**Comment by xamax71** [comment]
Hi, 
I'm on an ARM device running Ubuntu 20.04. Chromium is not available in my repo but Vivaldi released an arm version that you can install by adding their repo.

Added `SNAPPDF_CHROMIUM_PATH=/usr/bin/vivaldi` to the .env file

Now when I run
`./vendor/bin/snappdf convert --html "<h1>Hello world</h1>" save.pdf`

I get
`In Snappdf.php line 84:

  Downloaded Chromium binary is not executable. Make sure to set correct permissions (0755)`

I am not sure how to fix this.
Thanks
