### ISSUE TITLE
"file_get_contents(): Argument #1 ($filename) must not contain any null bytes" on Windows 11

### ISSUE THREAD

**Issue by Niiidro** [beganovich/snappdf#31]
Im getting the Error: file_get_contents(): Argument #1 ($filename) must not contain any null bytes  on Windows 11.

I've deleted the file_get_contents function on the return of the executeOnWindows function which fixed it for me.
I dont know if this is just a Windows 11 Issue. 

Im happy to help if you need more information from me

**Comment by beganovich** [comment]
Hi,

Thanks for reporting this. Is it possible to provide a failing test?

**Comment by beganovich** [comment]
Sure, please include stack trace. Make sure to remove sensitive data.

**Comment by benwilson** [comment]
Still an issue.  #32 fixed it for me.
