### ISSUE TITLE
question: relative paths

### ISSUE THREAD

**Issue by str** [beganovich/snappdf#35]
I'm trying to export a Laravel view to PDF like this:

```php
$view = view('laravel.blade.view', $args);
$pdf   = $snap->setHtml($view)->generate();

header("Content-type:application/pdf");
header("Content-Disposition:inline;filename=\"pdf.pdf\"");
return $pdf;
```

1) is there a way to generate the headers needed from SnapPDF?
2) the HTML loads CSS and JS with relative paths like

```HTML
<script src="/public/js/myscript.js"></script>
```

BUT because the browser can't find those relative paths, they are not loaded.  Is there a way to tell the browser it's base URL where to load the relative paths, without modifying the HTML?

Thank you.

**Comment by turbo124** [comment]
Snappdf has no idea about anything unless you explicitly define it. even if it knew about the relative path, it would still need to know the host to resolve etc etc.

**Comment by str** [comment]
@turbo124 right. I thought so. And even so, it's not SnapPDF, but chrome who has to know it.  I was trying to find the flag to send to chrome to set the root for the relative paths, but I'm not able to find how.   

I thought other SnapPDF users might bumped with the same issue and found a way around it.

**Comment by turbo124** [comment]
We use snappdf heavily, why not just inject the js directly into the html... you can prerender the blade template and then just get snappdf to render the html.

**Comment by str** [comment]
@turbo124 there are multiple workarounds, like injecting the JS into the HTML, but that would mean to modify every view we want to convert to PDF, and it is very prone to errors of forgetting to do that everywhere.

I was looking more of a global flag where to set the base URL to the browser to know where to look for the relative paths, so I don't have to go and modify every single <script>, <link>, <img> etc... both from current and future code.

**Comment by beganovich** [comment]
You can try to use HTML base tag.

```html
<head>
    <base href="https://google.com">
</head>

<h1>Hello, world</h1>

<script src="./script.js"></script>
```

The following code will try to load script.js from `https://google.com/script.js`.

**Comment by str** [comment]
@beganovich , sadly, base is another workaround, with it's own issues (like [1](https://stackoverflow.com/questions/26677580/base-tag-not-working-correctly), or [2](https://stackoverflow.com/questions/3211142/how-to-solve-a-problem-with-base-tag)), not the solution.

**Comment by beganovich** [comment]
Unfortunately, without some hacky rewrites and possible JS injection, I don't think we can do much. 

If you're using modern templating language or JSX, there probably should be some asset helper, like Laravel's `url` or `asset` to help your resolve this properly.
