### ISSUE TITLE
Timezone adjustment for PDF headers

### ISSUE THREAD

**Issue by benwilson** [beganovich/snappdf#36]
If you enable headers on a PDF, it will use server time. Setting an environment variable allows you to adjust the timezone. I don't know how standard this will be for the Chromium team moving forward, but I required a correct time header for one of my use cases.

Example: `export TZ="America/New_York";`

Prepending to the command string for Chromium will show headers with a localized date and time. Works in my Linux environments, not sure about Windows.

I did implement a `setTimezone()`, but I've also removed symphony dependencies from the version I'm using, so unfortunately no PR.

And thanks for a nice lightweight library!

**Comment by beganovich** [comment]
Thanks for letting us know, it's useful knowing this!
