### ISSUE TITLE
Add support for delayed printing

### ISSUE THREAD

**Issue by beganovich** [beganovich/snappdf#4]
Add support for --virtual-time-budget flag, that will delay the print-to-pdf setting. This will help if people have to make ajax request or wait for some javascript to finish before triggering the render.

**Comment by ADmad** [comment]
In general it would be nice if all the command options passed here were configurable https://github.com/beganovich/snappdf/blob/b6b4bcbb0937fd9e468b7e6e080e69ec96a68001/src/Snappdf.php#L151-L171

P. S. Even though the command using `--no-margins` option, I do get margins in the PDF generated using examples in the readme.

**Comment by beganovich** [comment]
Hey there, I agree, at some point I'll make a fully controllable flags.

When it comes to no-margins, I think that's removed from newer versions. 

To avoid double margins, I use:

@page { margin: 0 } in the template.

**Comment by beganovich** [comment]
For configurable launch options, there will be separate pull request.

https://github.com/beganovich/snappdf/commit/63ad3f1a0eec7bffc3a3c85f286769fca9a33fd5
