### ISSUE TITLE
libnss3.so: cannot open shared object file

### ISSUE THREAD

**Issue by cmpscabral** [beganovich/snappdf#6]
Hi,
I tried to use this on Ubuntu 20.04.1 LTS (server), but it fails.

Running with php fails silently with ProcessFailedException. I copied the command generated and executed it directly and I get this error:

`vendor/beganovich/snappdf/versions/840819-Linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

I then tried to install libnss3 with:

`apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev`

but this installs 202 new packages (600MB total) - is this really required?

Thanks!

**Comment by beganovich** [comment]
Hey there,

I didn't document this (yet) but some dependencies may be required. It's not much I can do there unfortunately. 

Here's list of them:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by cmpscabral** [comment]
Thank you
